server:
  port: 7777


# Registry client configuration
eureka:
  instance:
    hostname: localhost
    nonSecurePort: 7777
    preferIpAddress: false
    health-check-url-path: actuator/health
    status-page-url-path: actuator/info
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/registry/eureka/

logging:
  level:
    com.backbase: DEBUG
    org.springframework: DEBUG

gateway:
  token:
    converter:
      url: http://token-converter/bb-authentication-token-converter-service/convert
  # Test environment credentials for secured actuator endpoints
  actuator:
    user: admin
    password: admin

spring:
  cloud:
    gateway:
      routes:
        # Support for Portal friendly URLs
        - id: portal
          uri: lb://portal
          order: 10
          predicates:
            - Path=/**
          filters:
            - PrefixPath=/portal
        # Support for Portal API URLs
        - id: portal-api
          uri: lb://portal
          order: 5
          predicates:
            - Path=/api/**
          filters:
            - StripPrefix=1
            - PrefixPath=/portal