#%RAML 1.0
---
#===============================================================
#  References:
#    - RAML Specification - https://github.com/raml-org/raml-spec/blob/master/versions/raml-10/raml-10.md
#===============================================================
title: Fee Specification
uses:
  traits: lib/traits/traits.raml
version: v1
baseUri: "service-api/{version}"
mediaType: application/json
protocols: [ HTTP, HTTPS ]
types:
  Fee:
    type: !include schemas/fee-get.json
#===============================================================
# API resource definitions
#===============================================================

/fee:
  get:
    is: [ traits.BadRequestError, traits.InternalServerError ]
    description: "Returns a fee for the exchange rate"
    responses:
      200:
        body:
          application/json:
            type: Fee
            example: !include examples/example-fee-get.json