---
### workaround for an issue in 2.18.0 release. Remove after 2.18.1
spring:
  profiles:
    active: live
---
### Live profile
spring:
  profiles: live
  datasource:
    driver-class-name: ${spring.datasource.driver-class-name}
    username: ${spring.datasource.username.cashflow-service}
    password: ${spring.datasource.password.cashflow-service}
    url: ${spring.datasource.url.cashflow-service}

backbase:
  cashflow:
    task-executor:
      core-pool-size: 32
      max-pool-size: 1024
      keep-alive-seconds: 8
      queue-capacity: 60
      allow-core-thread-time-out: false
    sync:
      interval: 600
      fetch-timeout: 1800
      fetch-timeout-job-interval: 60
      request-job-interval: 30
      status-update-job-interval: 10
      fetch-job-interval: 20
cashflow:
  forecast-horizon:
    week: 10
    day: 14
    month: 12
  history-horizon:
    week: 4
    day: 7
    month: 3
