---
### Live profile
spring:
  profiles: live
  datasource:
    driver-class-name: ${spring.datasource.driver-class-name}
    username: ${spring.datasource.username.arrangement-pandp-service}
    password: ${spring.datasource.password.arrangement-pandp-service}
    url: ${spring.datasource.url.arrangement-pandp-service}

backbase:
  security:
    mtls:
      enabled: false
    public:
      paths: "/**"

