check:
  enabled: false
  targets:
  - name: Authentication
    url: http://edge:8080/api/auth/actuator/health
  - name: 8080/api/provisioning
    url: http://edge:8080/api/provisioning/actuator/health
imports:
- repository: https://repo.backbase.com
  apikey: 
  username: username
  password: password
  statics:
  - /backbase-6-release/com/backbase/tools/cx/cx6-import-tool-cli/6.2.2/cx6-import-tool-cli-6.2.2.jar
  - /backbase-6-release/com/backbase/cxp/editorial-collection/b3554/editorial-collection-b3554.zip
  - /expert-release-local/com/backbase/web-sdk/collection/collection-bb-web-sdk/1.10.0/collection-bb-web-sdk-1.10.0.zip
  - /backbase-6-release/com/backbase/cxp/experience-manager/b3554/experience-manager-b3554.zip
  - /expert-release-local/com/backbase/cxp/collection-approvals/1.1.1/collection-approvals-1.1.1-page.zip
  - /expert-release-local/com/backbase/cxp/collection-approvals/1.1.1/collection-approvals-1.1.1-portal.zip
target:
  identity-scope: openid
  identity-grant-type: password
  identity-client-id: bb-tooling-client
  # identity-realm: backbase
  auth-url: http://proxy:8080/api/auth/login
  context: http://proxy:8080/api/provisioning
  password: admin
  retry-back-off-period: 2000
  retry-max-attempts: 200
  username: admin