---
### Live profile
spring:
  profiles: live
  datasource:
    driver-class-name: ${spring.datasource.driver-class-name}
    username: ${spring.datasource.username.payment-order-service}
    password: ${spring.datasource.password.payment-order-service}
    url: ${spring.datasource.url.payment-order-service}

logging:
  level:
    com.backbase: DEBUG
    org.springframework: DEBUG